#server:
#  port: 8888
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource: #数据源
#    url: jdbc:mysql://localhost:3306/pw?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false  # 数据库的 JDBC URL
#    username: cyd  #数据库的登录用户名
#    password: cyd   #数据库的登录密码
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false  # 数据库的 JDBC URL
    username: root  #数据库的登录用户名
    password: root   #数据库的登录密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-handlers-package: com.pw
#  mapper-locations: classpath:/mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: com.pw.**.domain;com.pw.**.dto;com.pw.**.vo;
  #  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    #    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler



springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-model-v3: true

knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
#  basic:
#    enable: true
#    username: admin
#    password: 123456