server:
  port: 5008
spring:
  redis:
    host: 1.92.159.74
    port: 6379
    password: 123456
    database: 0 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource: #数据源
    url: jdbc:mysql://120.48.127.181:3306/pw?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false  # 数据库的 JDBC URL
    username: cyd  #数据库的登录用户名
    password: cyd   #数据库的登录密码
    #    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false  # 数据库的 JDBC URL
    #    username: root  #数据库的登录用户名
    #    password: root   #数据库的登录密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
  # 邮箱 SMTP 配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 1205489124@qq.com
    password: keyjcuwigjlhhfac
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-handlers-package: com.pw
  #  mapper-locations: classpath:/mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: com.pw.**.domain;com.pw.**.dto;com.pw.**.vo;
  #  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    #    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler



springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-model-v3: true

knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
#  basic:
#    enable: true
#    username: admin
#    password: 123456
