/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlankTemplate: typeof import('./src/components/BlankTemplate.vue')['default']
    CommonAside: typeof import('./src/components/CommonAside.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    Directory: typeof import('./src/components/Directory/directory.vue')['default']
    ElButtton: typeof import('element-plus/es')['ElButtton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FloatButton: typeof import('./src/components/floatButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistogramChart: typeof import('./src/components/charts/histogramChart.vue')['default']
    LineChart: typeof import('./src/components/charts/lineChart.vue')['default']
    NavMenuItem: typeof import('./src/components/NavMenuItem.vue')['default']
    RadarChart: typeof import('./src/components/charts/radarChart.vue')['default']
    RandomSlogan: typeof import('./src/components/RandomSlogan.vue')['default']
    RingChart: typeof import('./src/components/charts/ringChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
